#server.address=<Your IP>
#server.port=<Your Port>

spring:
  application:
    name: SchoolShop
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SchoolShop
    username: root
    password: 123456
  session:
    store-type: redis
    timeout: 864000
  redis:
    database: 1
    host: localhost
    port: 8888
    timeout: 5000
server:
  port: 8080
  servlet:
    context-path:
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl