#server.address=<Your IP>
#server.port=<Your Port>
#

#配置数据库的连接信息 - 四要素
#驱动类名称
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#数据库连接的url
spring.datasource.url=jdbc:mysql://localhost:3306/SchoolShop
#连接数据库的用户名
spring.datasource.username=root
#连接数据库的密码
spring.datasource.password=123456

spring:
  application:
    name: SchoolShop
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SchoolShop
    username: root
    password: 123456
  session:
    store-type: redis
    timeout: 864000
  redis:
    database: 1
    host: localhost
    port: 8888
    timeout: 5000
server:
  port: 8080
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl